version: "2"

services:
  mysql5:
    container_name: mysql5
    image: mysql:5.5.60
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    networks:
      - yii-docker
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.13
    ports:
      - 443:443
      - 6060:6060
      - 5553:5553
    volumes:
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./www/:/var/www/
    networks:
      - yii-docker
  php5:
    container_name: php5
    restart: always
    image: php:5.6-fpm
    volumes:
      - ./www/:/var/www/
      - ./conf/php/:/usr/local/etc/php/conf.d/
    expose: 
      - 9000
    networks:
      - yii-docker
    command: 
      - /bin/bash
      - -c
      - |
          docker-php-ext-install pdo_mysql mysqli 
          apt-get update -y
          apt-get install -y libfreetype6-dev
          apt-get install -y libjpeg62-turbo-dev
          apt-get install -y libmcrypt-dev
          apt-get install -y libpng-dev
          apt-get install -y zlib1g-dev
          docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          docker-php-ext-install mbstring zip gd 
          php-fpm
networks:
  yii-docker:
    driver: bridge





